### ISSUE TITLE
Integrate with MTEB

### ISSUE THREAD

**Issue by Muennighoff** [gentaiscool/miners#1]
Amazing work 🚀 Would be cool to integrate this work with MTEB - opened an issue here: https://github.com/embeddings-benchmark/mteb/issues/907 😇

**Comment by gentaiscool** [comment]
Hi Niklas @Muennighoff I think it is a very good idea. Let me find some time to wrap up the data.

**Comment by gentaiscool** [comment]
Thank you for the suggestion. I have wrapped up some data and integrated them to the benchmark.
